name: fasttext
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.08.22
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.11
  - pip=23.3
  - python=3.9.18
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - fasttext==0.9.2
      - gensim==3.8.3
      - jpype1==1.4.1
      - konlpy==0.6.0
      - lxml==4.9.3
      - numpy==1.26.1
      - packaging==23.2
      - pybind11==2.11.1
      - scipy==1.11.3
      - six==1.16.0
      - smart-open==6.4.0
      - tqdm==4.66.1
